# Sesi 2 — Bagian 2.2: Library untuk Pemrosesan Data

Kita akan menjawab **tiga pertanyaan bisnis** dari dataset penjualan `products.csv`:
1. Produk mana yang paling banyak terjual?
2. Berapa rata-rata harga per kategori?
3. Kategori mana yang stoknya paling rendah?

## Persiapan: install & import library
Aktifkan virtual environment Sesi 1 dulu (atau kita buat environment baru di Sesi 2), lalu jalankan di terminal:
`pip install numpy pandas`

In [1]:
!pip install numpy pandas

Requirement already satisfied: numpy in c:\users\ysrfa\appdata\local\programs\python\python313\lib\site-packages (2.2.6)
Requirement already satisfied: pandas in c:\users\ysrfa\appdata\local\programs\python\python313\lib\site-packages (2.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ysrfa\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ysrfa\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ysrfa\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\ysrfa\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: C:\Users\ysrfa\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [3]:
import numpy as np
import pandas as pd

pd.read_csv("products.csv")

              name  category  price  sold  stock
0        Kopi Susu  Beverage  25000   320     45
1        Teh Manis  Beverage  15000   410     60
2      Air Mineral  Beverage   8000   520    120
3        Jus Jeruk  Beverage  22000   180     30
4      Nasi Goreng      Food  30000   275     25
5         Mie Ayam      Food  28000   240     18
6      Ayam Geprek      Food  32000   300     22
7       Roti Bakar     Snack  18000   150     40
8   Kentang Goreng     Snack  20000   210     35
9    Pisang Coklat     Snack  17000   130     12
10           Donat     Snack  12000    95      8
11       Croissant     Snack  23000    70     15

## NumPy: kalkulator untuk deret angka

In [4]:
# TODO: buat np.array dari [10, 20, 30] lalu cetak rata-ratanya (.mean())
angka = np.array([10,20,30])
print(angka.mean())

20.0

## Load: baca file menjadi DataFrame

In [7]:
# TODO: baca "products.csv" ke dalam df, lalu tampilkan df.head()
df = pd.read_csv("products.csv")
df.head(3)

          name  category  price  sold  stock
0    Kopi Susu  Beverage  25000   320     45
1    Teh Manis  Beverage  15000   410     60
2  Air Mineral  Beverage   8000   520    120

## Filter: ambil baris yang kita perlukan

In [8]:
# TODO: filter df untuk kategori "Beverage"
df[df["category"]=="Food"]

          name category  price  sold  stock
4  Nasi Goreng     Food  30000   275     25
5     Mie Ayam     Food  28000   240     18
6  Ayam Geprek     Food  32000   300     22

---
## Filter dengan Banyak Multiple Condition
Gabungkan kondisi menggunakan `&` (AND) dan `|` (OR), gunakan tanda kurung di tiap kondisi

In [11]:
# TODO: filter Beverage yang harganya di bawah 20000
# df[...]
df[((df["category"]=="Beverage")&(df["price"] < 20000))]

          name  category  price  sold  stock
1    Teh Manis  Beverage  15000   410     60
2  Air Mineral  Beverage   8000   520    120

---
## Membuat Kolom Baru (Computed Column)
Kita bisa membuat kolom baru berdasarkan nilai dari kolom - kolom yang sudah ada. Contohnya: kita buat kolom `revenue` sebagai hasil perhitungan `harga` × `terjual`.

In [ ]:
# TODO: buat kolom baru "revenue" = df["price"] * df["sold"]

# TODO: tampilkan kolom name, price, sold, revenue pakai df[[...]].head()

---
## Urutkan (sort) Beberapa Kolom Sekaligus

In [ ]:
# TODO: sort berdasarkan category (ascending) lalu revenue (descending)
# df.sort_values(by=[...], ascending=[...])

---
## value_counts: Hitung Jumlah per Kategori

In [ ]:
# TODO: hitung jumlah produk per category pakai .value_counts()

## Pertanyaan 1 — Produk paling banyak terjual
Urutkan berdasarkan kolom `sold` dari besar ke kecil, ambil teratas.

In [13]:
# TODO: sort_values pada "sold", ascending=False, ambil .head(1)
df.sort_values("sold", ascending=True).head(1)

         name category  price  sold  stock
11  Croissant    Snack  23000    70     15

## Pertanyaan 2 — Rata-rata harga per kategori
Kelompokkan (`groupby`) berdasarkan kategori, hitung rata-rata harga.

In [14]:
# TODO: groupby "category", ambil kolom "price", hitung .mean()
df.groupby("category")["price"].mean()

category
Beverage    17500.0
Food        30000.0
Snack       18000.0
Name: price, dtype: float64

## Pertanyaan 3 — Kategori dengan stok paling rendah
Jumlahkan stok per kategori, lalu cari yang terkecil.

In [16]:
# TODO: groupby "category", sum kolom "stock",
#       lalu gunakan .idxmin() untuk cari kategori terendah
df.groupby("category")["stock"].sum().idxmin()

'Food'

---
## Simpan DataFrame ke file CSV

In [ ]:
# TODO: simpan df ke file "products_analyzed.csv"
# perhatikan: index=False agar kolom index tidak ikut tersimpan
# df.to_csv(...)